DROP DATABASE IF EXISTS burger_db;

CREATE DATABASE burger_db;

USE burger_db;

CREATE TABLE burgers (
id INT NOT NULL AUTO_INCREMENT,
burger_name VARCHAR(200) NOT NULL,
devoured BOOLEAN DEFAULT false,
DATE TIMESTAMP,

PRIMARY KEY (id)
 )

--ALTER TABLE burgers CHANGE COLUMN createdAt datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
--ALTER TABLE burgers CHANGE COLUMN updatedAt datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
