CREATE DATABASE burger_db;

USE burger_db;

CREATE TABLE burgers (
id INT(20) AUTO_INCREMENT NOT NULL,
burger_name VARCHAR(50) NOT NULL,
devoured BOOLEAN,
DATE TIMESTAMP,

PRIMARY KEY (id)
 );
 
--ALTER TABLE burgers CHANGE COLUMN createdAt datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
--ALTER TABLE burgers CHANGE COLUMN updatedAt datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;
